# name: Django Deployment

# on:
#   push:
#     branches:
#       - master
# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Executing remote SSH deploy script
#         uses: appleboy/ssh-action@v1.1.0
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.KEY }}
#           script: |
#             set -e
#             pwd
#             cd chess-game/
#             git pull origin master
#             source myenv/bin/activate
#             python3 manage.py migrate
#             pip3 install -r requirements.txt